name: nodejs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      # Install locked dependencies and prepare types
      - run: pnpm i
      - run: pnpm run dev:prepare

      # Check if build and package artifacts can still be generated
      - run: pnpm run prepack

      # Check linting and typing
      - run: pnpm run lint
      - run: pnpm run types

      # Check building
      - run: pnpm run dev:build
      - run: pnpm run client:build
